### ISSUE TITLE
Interface development

### ISSUE THREAD

**Issue by Harshal141** [Harshal141/DigitalResumer#10]
We are currently workign on the backend and in the mean time need to design a simple frontend page for the view resume section.

You need to design the below attached interface.
![image](https://github.com/Harshal141/ResumeWorded/assets/91362856/595e59cc-5dad-4c44-bdbc-1cab28ab44f7)

Implement this interface in the `/resume` section.
/client/src/pages/Resume/Resume.js

**Comment by Ejay02** [comment]
This is blank, is there meant to be more?

**Comment by Harshal141** [comment]
Can you expalin what you mean my blank, and what is blank 
@Ejay02

**Comment by Ejay02** [comment]
oh, it's just a new page, so was wondering if there's meant to be more or another screen. 
![image](https://github.com/Harshal141/ResumeWorded/assets/66236069/03f2a3ba-6f08-41d1-8221-c52eb2606882)

**Comment by Harshal141** [comment]
Yup, you want to take this task? @Ejay02

**Comment by Ejay02** [comment]
yes. adding icons and taking out the border

**Comment by Harshal141** [comment]
This is not a blank page 😂 this is a div with styling to look like a screen, so its a page with the small screen like design inside it.
You have to design this:
![image](https://github.com/Harshal141/ResumeWorded/assets/91362856/5e50adee-1bd7-40a1-8b57-2898777a2a2d)

- Can you add one comment about what you understand about the task, so i know you are working on the right thing

And if any queries feel free to tag, 
cc: @Ejay02

**Comment by Ejay02** [comment]
What I understand is a navbar that holds the 🔒 and username and to the far right a download icon.
The nav div is dark with a white body

**Comment by Harshal141** [comment]
ok you got 50% correct but this is not the navbar.
This is the final product this is a fake screen in the page: 
![image](https://github.com/Harshal141/ResumeWorded/assets/91362856/7922e43b-e08c-419a-891f-5118522d7dfe)

Now do you understand what it is?

**Comment by Ejay02** [comment]
a blank screen mac screen in a page.
 a dark background that holds a page. this page has the top div which has the lock and username to the right a download icon. I'll take it this includes the mac icons too [to the left]

**Comment by algoplutus1708** [comment]
Hy please assign me this issue I can resolve it

**Comment by Harshal141** [comment]
Sorry @algoplutus1708 i already assigned it to @Ejay02 
he will be working on it. I will look for another issue for you.

**Comment by Ejay02** [comment]
@Harshal141 you can assign it to @algoplutus1708. I just realized it is react, my react is rusty. 😔

**Comment by Harshal141** [comment]
Ok @algoplutus1708 you can work on this
